import { IUser } from "@/types/user.types";

const mockUsers: IUser[] = [
  {
    id: 1,
    email: "user1@example.com",
    name: "John Doe",
    role: "WHITE_LABEL_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: null,
    permissions: ["VIEW_DASHBOARD", "VIEW_SHIPMENT", "CREATE_USER"],
    credits: 100,
  },
  {
    id: 2,
    email: "user2@example.com",
    name: "Jane Smith",
    role: "CLIENT_SUPER_USER",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: 2,
    permissions: ["VIEW_DASHBOARD", "EDIT_SHIPMENT"],
    credits: 200,
  },
  {
    id: 3,
    email: "user3@example.com",
    name: "Alice Johnson",
    role: "SUPER_ADMIN",
    isActive: false,
    status: "REJECTED",
    companyId: null,
    clientId: null,
    permissions: ["VIEW_USER", "CREATE_USER", "DELETE_USER"],
    credits: 150,
  },
  {
    id: 4,
    email: "user4@example.com",
    name: "Bob Brown",
    role: "CLIENT_USER",
    isActive: true,
    status: "REQUESTED",
    companyId: 3,
    clientId: 4,
    permissions: ["VIEW_SHIPMENT"],
    credits: 50,
  },
  {
    id: 5,
    email: "user5@example.com",
    name: "Charlie Davis",
    role: "SUB_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: null,
    clientId: null,
    permissions: ["VIEW_DASHBOARD", "EDIT_USER", "VIEW_COMPANY"],
    credits: 300,
  },
  {
    id: 6,
    email: "user6@example.com",
    name: "David Evans",
    role: "WHITE_LABEL_SUB_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 2,
    clientId: 5,
    permissions: ["VIEW_USER", "CREATE_SHIPMENT", "DELETE_SHIPMENT"],
    credits: 120,
  },
  {
    id: 7,
    email: "user7@example.com",
    name: "Eve Foster",
    role: "WHITE_LABEL_ADMIN",
    isActive: false,
    status: "REJECTED",
    companyId: 1,
    clientId: 6,
    permissions: ["VIEW_SHIPMENT", "EDIT_SHIPMENT", "VIEW_COMPANY"],
    credits: 180,
  },
  {
    id: 8,
    email: "user8@example.com",
    name: "Frank Green",
    role: "CLIENT_SUPER_USER",
    isActive: true,
    status: "APPROVED",
    companyId: 2,
    clientId: 7,
    permissions: ["CREATE_SHIPMENT", "DELETE_USER"],
    credits: 220,
  },
  {
    id: 9,
    email: "user9@example.com",
    name: "Grace Harris",
    role: "CLIENT_USER",
    isActive: true,
    status: "REQUESTED",
    companyId: 4,
    clientId: 8,
    permissions: ["VIEW_SHIPMENT", "EDIT_SHIPMENT"],
    credits: 90,
  },
  {
    id: 10,
    email: "user10@example.com",
    name: "Hank Irving",
    role: "SUPER_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: null,
    clientId: null,
    permissions: ["VIEW_USER", "EDIT_USER", "DELETE_USER"],
    credits: 400,
  },
  {
    id: 11,
    email: "user11@example.com",
    name: "Ivy Johnson",
    role: "SUB_ADMIN",
    isActive: false,
    status: "REJECTED",
    companyId: 3,
    clientId: 9,
    permissions: ["VIEW_DASHBOARD", "VIEW_SHIPMENT", "VIEW_COMPANY"],
    credits: 130,
  },
  {
    id: 12,
    email: "user12@example.com",
    name: "Jack King",
    role: "WHITE_LABEL_SUB_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: 10,
    permissions: ["VIEW_USER", "CREATE_SHIPMENT"],
    credits: 210,
  },
  {
    id: 13,
    email: "user13@example.com",
    name: "Karen Lee",
    role: "WHITE_LABEL_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: null,
    permissions: ["VIEW_DASHBOARD", "VIEW_SHIPMENT", "CREATE_USER"],
    credits: 110,
  },
  {
    id: 14,
    email: "user14@example.com",
    name: "Leo Martin",
    role: "CLIENT_SUPER_USER",
    isActive: false,
    status: "REJECTED",
    companyId: 2,
    clientId: 11,
    permissions: ["VIEW_DASHBOARD", "EDIT_SHIPMENT"],
    credits: 250,
  },
  {
    id: 15,
    email: "user15@example.com",
    name: "Mona Nelson",
    role: "SUPER_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: null,
    clientId: null,
    permissions: ["VIEW_USER", "CREATE_USER", "DELETE_USER"],
    credits: 350,
  },
  {
    id: 16,
    email: "user16@example.com",
    name: "Nate Owen",
    role: "CLIENT_USER",
    isActive: true,
    status: "REQUESTED",
    companyId: 4,
    clientId: 12,
    permissions: ["VIEW_SHIPMENT"],
    credits: 60,
  },
  {
    id: 17,
    email: "user17@example.com",
    name: "Olive Perez",
    role: "SUB_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 3,
    clientId: null,
    permissions: ["VIEW_DASHBOARD", "EDIT_USER", "VIEW_COMPANY"],
    credits: 330,
  },
  {
    id: 18,
    email: "user18@example.com",
    name: "Paul Quinn",
    role: "WHITE_LABEL_SUB_ADMIN",
    isActive: false,
    status: "REJECTED",
    companyId: 2,
    clientId: 13,
    permissions: ["VIEW_USER", "CREATE_SHIPMENT", "DELETE_SHIPMENT"],
    credits: 150,
  },
  {
    id: 19,
    email: "user19@example.com",
    name: "Quincy Roberts",
    role: "WHITE_LABEL_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: null,
    permissions: ["VIEW_SHIPMENT", "EDIT_SHIPMENT", "VIEW_COMPANY"],
    credits: 190,
  },
  {
    id: 20,
    email: "user20@example.com",
    name: "Rachel Smith",
    role: "CLIENT_SUPER_USER",
    isActive: true,
    status: "APPROVED",
    companyId: 2,
    clientId: 14,
    permissions: ["CREATE_SHIPMENT", "DELETE_USER"],
    credits: 230,
  },
  {
    id: 21,
    email: "user21@example.com",
    name: "Sam Thompson",
    role: "CLIENT_USER",
    isActive: true,
    status: "REQUESTED",
    companyId: 4,
    clientId: 15,
    permissions: ["VIEW_SHIPMENT", "EDIT_SHIPMENT"],
    credits: 100,
  },
  {
    id: 22,
    email: "user22@example.com",
    name: "Tina Underwood",
    role: "SUPER_ADMIN",
    isActive: false,
    status: "REJECTED",
    companyId: null,
    clientId: null,
    permissions: ["VIEW_USER", "EDIT_USER", "DELETE_USER"],
    credits: 410,
  },
  {
    id: 23,
    email: "user23@example.com",
    name: "Uma Valentine",
    role: "SUB_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 3,
    clientId: 16,
    permissions: ["VIEW_DASHBOARD", "VIEW_SHIPMENT", "VIEW_COMPANY"],
    credits: 140,
  },
  {
    id: 24,
    email: "user24@example.com",
    name: "Vince Williams",
    role: "WHITE_LABEL_SUB_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: 17,
    permissions: ["VIEW_USER", "CREATE_SHIPMENT"],
    credits: 220,
  },
  {
    id: 25,
    email: "user25@example.com",
    name: "Wendy Xavier",
    role: "WHITE_LABEL_ADMIN",
    isActive: true,
    status: "APPROVED",
    companyId: 1,
    clientId: null,
    permissions: ["VIEW_DASHBOARD", "VIEW_SHIPMENT", "CREATE_USER"],
    credits: 160,
  },
];



const LIMIT = 10;
export const paginatedMockUser = {
  results: mockUsers,
  paginatorInfo: {
    skip: 0,
    limit: 10,
    currentPage: 1,
    pages: 3,
    hasNextPage: true,
    totalRecords: 25,
    pageSize: LIMIT,
  },
};
